name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Run tests
      run: swift test -v
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    container:
      image: swift:5.2

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Run tests
      run: swift test -v
